package edu.ucan.sdp2.conectacore.enums;

public enum TipoEvento {
    TRANSFERENCIA_REALIZADA,
    REQUISICAO_TRANSFERENCIA,
    REQUISICAO_CREDITO,
    APROVACAO_CREDITO,
    REALIZACAO_CREDITO,
    ROLLBACK_TRANSFERENCIA,
    REQUISICAO_INFO_CONTA,
    REQUISICAO_TRANSACAO_CONTA,
}
